version: '3.8'

services:
  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=3447Turkey!!_
    volumes:
      - /opt/app_data/sqlserver/data:/var/opt/mssql/data
      - /opt/app_data/sqlserver/log:/var/opt/mssql/log
